# Generated by Django 4.1.2 on 2022-10-30 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='The username must be a minimum of 2 chars')]),
        ),
    ]
